# Generated by Django 3.2.6 on 2021-09-06 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20210906_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('brand', models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('price', models.IntegerField()),
                ('detail', models.TextField()),
                ('file', models.FileField(upload_to='static/uploads')),
            ],
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
