# Generated by Django 3.2.6 on 2021-09-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_auto_20210906_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
    ]
