# Generated by Django 3.2.7 on 2021-09-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_adminprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
