# Generated by Django 3.2.7 on 2021-09-27 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0002_order_delerivered_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('Events', models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('date', models.DateTimeField()),
                ('detail', models.TextField()),
                ('file', models.FileField(upload_to='static/uploads')),
            ],
        ),
    ]
