# Generated by Django 4.0 on 2022-02-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0004_eventregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRegister',
        ),
    ]
